// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzqwrennqhafsqjjruhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6cXdyZW5ucWhhZnNxampydWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NDg3NDUsImV4cCI6MjA1NzIyNDc0NX0.POyKHisN30A9ihlaOzcXl7sTEyRQAJUYhHjMaOqk-FM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);